<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;

/**
 * Seeds a curated set of essential tags without requiring API access.
 * Run danbooru:import afterwards for a more complete set.
 */
class TagSeeder extends Seeder
{
    public function run(): void
    {
        $tags = [
            // ── CHARACTER ────────────────────────────────────────────────
            // hair_color
            ['name' => 'blonde_hair',    'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 900000, 'is_nsfw' => false],
            ['name' => 'brown_hair',     'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 800000, 'is_nsfw' => false],
            ['name' => 'black_hair',     'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 750000, 'is_nsfw' => false],
            ['name' => 'blue_hair',      'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'red_hair',       'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'white_hair',     'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 350000, 'is_nsfw' => false],
            ['name' => 'silver_hair',    'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'pink_hair',      'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 280000, 'is_nsfw' => false],
            ['name' => 'purple_hair',    'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 250000, 'is_nsfw' => false],
            ['name' => 'green_hair',     'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'orange_hair',    'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'grey_hair',      'section' => 'character', 'subsection' => 'hair_color', 'post_count' => 120000, 'is_nsfw' => false],
            ['name' => 'teal_hair',      'section' => 'character', 'subsection' => 'hair_color', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'multicolored_hair','section'=> 'character', 'subsection' => 'hair_color', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'gradient_hair',  'section' => 'character', 'subsection' => 'hair_color', 'post_count' =>  70000, 'is_nsfw' => false],
            ['name' => 'streaked_hair',  'section' => 'character', 'subsection' => 'hair_color', 'post_count' =>  60000, 'is_nsfw' => false],
            ['name' => 'dark_blue_hair', 'section' => 'character', 'subsection' => 'hair_color', 'post_count' =>  50000, 'is_nsfw' => false],
            ['name' => 'light_blue_hair','section' => 'character', 'subsection' => 'hair_color', 'post_count' =>  40000, 'is_nsfw' => false],

            // hair_length
            ['name' => 'short_hair',       'section' => 'character', 'subsection' => 'hair_length', 'post_count' => 1200000, 'is_nsfw' => false],
            ['name' => 'long_hair',        'section' => 'character', 'subsection' => 'hair_length', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => 'medium_hair',      'section' => 'character', 'subsection' => 'hair_length', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'very_long_hair',   'section' => 'character', 'subsection' => 'hair_length', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'absurdly_long_hair','section'=> 'character', 'subsection' => 'hair_length', 'post_count' =>   80000, 'is_nsfw' => false],
            ['name' => 'bob_cut',          'section' => 'character', 'subsection' => 'hair_length', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'pixie_cut',        'section' => 'character', 'subsection' => 'hair_length', 'post_count' =>   30000, 'is_nsfw' => false],

            // hair_style
            ['name' => 'twintails',       'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'ponytail',        'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 700000, 'is_nsfw' => false],
            ['name' => 'braid',           'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'twin_braids',     'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'side_ponytail',   'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'ahoge',           'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 250000, 'is_nsfw' => false],
            ['name' => 'drill_hair',      'section' => 'character', 'subsection' => 'hair_style', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'hime_cut',        'section' => 'character', 'subsection' => 'hair_style', 'post_count' =>  90000, 'is_nsfw' => false],
            ['name' => 'hair_bun',        'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'wavy_hair',       'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 180000, 'is_nsfw' => false],
            ['name' => 'curly_hair',      'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 120000, 'is_nsfw' => false],
            ['name' => 'straight_hair',   'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'messy_hair',      'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'low_twintails',   'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'two_side_up',     'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 120000, 'is_nsfw' => false],
            ['name' => 'sidelocks',       'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'bangs',           'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 800000, 'is_nsfw' => false],
            ['name' => 'blunt_bangs',     'section' => 'character', 'subsection' => 'hair_style', 'post_count' => 200000, 'is_nsfw' => false],

            // eye_color
            ['name' => 'blue_eyes',       'section' => 'character', 'subsection' => 'eye_color', 'post_count' => 1000000, 'is_nsfw' => false],
            ['name' => 'red_eyes',        'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  600000, 'is_nsfw' => false],
            ['name' => 'green_eyes',      'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'brown_eyes',      'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  450000, 'is_nsfw' => false],
            ['name' => 'purple_eyes',     'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  350000, 'is_nsfw' => false],
            ['name' => 'golden_eyes',     'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'yellow_eyes',     'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  280000, 'is_nsfw' => false],
            ['name' => 'pink_eyes',       'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'grey_eyes',       'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  120000, 'is_nsfw' => false],
            ['name' => 'white_eyes',      'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>   80000, 'is_nsfw' => false],
            ['name' => 'black_eyes',      'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>   70000, 'is_nsfw' => false],
            ['name' => 'heterochromia',   'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'aqua_eyes',       'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'amber_eyes',      'section' => 'character', 'subsection' => 'eye_color', 'post_count' =>  100000, 'is_nsfw' => false],

            // eye_shape
            ['name' => 'tareme',          'section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'tsurime',         'section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'half-closed_eyes','section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'wide_eyes',       'section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'wink',            'section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'glowing_eyes',    'section' => 'character', 'subsection' => 'eye_shape', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'empty_eyes',      'section' => 'character', 'subsection' => 'eye_shape', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'heart-shaped_eyes','section'=> 'character', 'subsection' => 'eye_shape', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'star-shaped_pupils','section'=> 'character','subsection' => 'eye_shape', 'post_count' =>  60000, 'is_nsfw' => false],
            ['name' => 'slit_pupils',     'section' => 'character', 'subsection' => 'eye_shape', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'sparkling_eyes',  'section' => 'character', 'subsection' => 'eye_shape', 'post_count' =>  70000, 'is_nsfw' => false],

            // skin_color
            ['name' => 'dark_skin',         'section' => 'character', 'subsection' => 'skin_color', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'pale_skin',         'section' => 'character', 'subsection' => 'skin_color', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'tan',               'section' => 'character', 'subsection' => 'skin_color', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'tanned',            'section' => 'character', 'subsection' => 'skin_color', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'dark-skinned_female','section'=> 'character', 'subsection' => 'skin_color', 'post_count' => 120000, 'is_nsfw' => false],
            ['name' => 'olive_skin',        'section' => 'character', 'subsection' => 'skin_color', 'post_count' =>  30000, 'is_nsfw' => false],

            // breast_size (NSFW)
            ['name' => 'flat_chest',       'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 600000, 'is_nsfw' => true],
            ['name' => 'small_breasts',    'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'medium_breasts',   'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 300000, 'is_nsfw' => true],
            ['name' => 'large_breasts',    'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 800000, 'is_nsfw' => true],
            ['name' => 'huge_breasts',     'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'gigantic_breasts', 'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'cleavage',         'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 700000, 'is_nsfw' => true],
            ['name' => 'sideboob',         'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'underboob',        'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'nipples',          'section' => 'character', 'subsection' => 'breast_size', 'post_count' => 500000, 'is_nsfw' => true],

            // body_type (NSFW)
            ['name' => 'thick_thighs',    'section' => 'character', 'subsection' => 'body_type', 'post_count' => 500000, 'is_nsfw' => true],
            ['name' => 'wide_hips',       'section' => 'character', 'subsection' => 'body_type', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'curvy',           'section' => 'character', 'subsection' => 'body_type', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'petite',          'section' => 'character', 'subsection' => 'body_type', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'muscular',        'section' => 'character', 'subsection' => 'body_type', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'muscular_female', 'section' => 'character', 'subsection' => 'body_type', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'abs',             'section' => 'character', 'subsection' => 'body_type', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'plump',           'section' => 'character', 'subsection' => 'body_type', 'post_count' => 100000, 'is_nsfw' => true],
            ['name' => 'big_ass',         'section' => 'character', 'subsection' => 'body_type', 'post_count' => 300000, 'is_nsfw' => true],
            ['name' => 'ass',             'section' => 'character', 'subsection' => 'body_type', 'post_count' => 800000, 'is_nsfw' => true],
            ['name' => 'nude',            'section' => 'character', 'subsection' => 'body_type', 'post_count' => 900000, 'is_nsfw' => true],
            ['name' => 'naked',           'section' => 'character', 'subsection' => 'body_type', 'post_count' => 600000, 'is_nsfw' => true],

            // age_appearance
            ['name' => '1girl',           'section' => 'character', 'subsection' => 'age_appearance', 'post_count' => 5000000, 'is_nsfw' => false],
            ['name' => '1boy',            'section' => 'character', 'subsection' => 'age_appearance', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => '2girls',          'section' => 'character', 'subsection' => 'age_appearance', 'post_count' => 1000000, 'is_nsfw' => false],
            ['name' => 'solo',            'section' => 'character', 'subsection' => 'age_appearance', 'post_count' => 4000000, 'is_nsfw' => false],
            ['name' => 'mature_female',   'section' => 'character', 'subsection' => 'age_appearance', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'milf',            'section' => 'character', 'subsection' => 'age_appearance', 'post_count' =>  200000, 'is_nsfw' => true],
            ['name' => 'multiple_girls',  'section' => 'character', 'subsection' => 'age_appearance', 'post_count' =>  800000, 'is_nsfw' => false],
            ['name' => 'older_female',    'section' => 'character', 'subsection' => 'age_appearance', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'younger_female',  'section' => 'character', 'subsection' => 'age_appearance', 'post_count' =>   80000, 'is_nsfw' => false],

            // animal_features
            ['name' => 'cat_ears',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 700000, 'is_nsfw' => false],
            ['name' => 'fox_ears',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'dog_ears',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'bunny_ears',      'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'wolf_ears',       'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'elf_ears',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'pointy_ears',     'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'cat_tail',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'fox_tail',        'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'angel_wings',     'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'demon_wings',     'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'horns',           'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'demon_horns',     'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'halo',            'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'tail',            'section' => 'character', 'subsection' => 'animal_features', 'post_count' => 500000, 'is_nsfw' => false],

            // special_features
            ['name' => 'scar',            'section' => 'character', 'subsection' => 'special_features', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'tattoo',          'section' => 'character', 'subsection' => 'special_features', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'freckles',        'section' => 'character', 'subsection' => 'special_features', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'mole',            'section' => 'character', 'subsection' => 'special_features', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'mole_under_eye',  'section' => 'character', 'subsection' => 'special_features', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'eyepatch',        'section' => 'character', 'subsection' => 'special_features', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'glowing',         'section' => 'character', 'subsection' => 'special_features', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'third_eye',       'section' => 'character', 'subsection' => 'special_features', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'cyborg',          'section' => 'character', 'subsection' => 'special_features', 'post_count' =>  80000, 'is_nsfw' => false],

            // ── POSES ─────────────────────────────────────────────────────
            ['name' => 'standing',        'section' => 'pose', 'subsection' => 'standing', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => 'walking',         'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'running',         'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'jumping',         'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'contrapposto',    'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'leaning_forward', 'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'leaning_back',    'section' => 'pose', 'subsection' => 'standing', 'post_count' =>   80000, 'is_nsfw' => false],
            ['name' => 'floating',        'section' => 'pose', 'subsection' => 'standing', 'post_count' =>  100000, 'is_nsfw' => false],

            ['name' => 'sitting',         'section' => 'pose', 'subsection' => 'sitting', 'post_count' => 1500000, 'is_nsfw' => false],
            ['name' => 'kneeling',        'section' => 'pose', 'subsection' => 'sitting', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'squatting',       'section' => 'pose', 'subsection' => 'sitting', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'seiza',           'section' => 'pose', 'subsection' => 'sitting', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'cross-legged',    'section' => 'pose', 'subsection' => 'sitting', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'hugging_knees',   'section' => 'pose', 'subsection' => 'sitting', 'post_count' =>   80000, 'is_nsfw' => false],

            ['name' => 'lying',           'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  800000, 'is_nsfw' => false],
            ['name' => 'on_back',         'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  600000, 'is_nsfw' => true],
            ['name' => 'on_stomach',      'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  300000, 'is_nsfw' => true],
            ['name' => 'on_side',         'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  200000, 'is_nsfw' => true],
            ['name' => 'sleeping',        'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'all_fours',       'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  300000, 'is_nsfw' => true],
            ['name' => 'bent_over',       'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  250000, 'is_nsfw' => true],
            ['name' => 'spread_eagle',    'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  150000, 'is_nsfw' => true],
            ['name' => 'arched_back',     'section' => 'pose', 'subsection' => 'lying', 'post_count' =>  200000, 'is_nsfw' => true],

            ['name' => 'arms_up',         'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'arms_behind_back','section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'arms_crossed',    'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'hand_on_hip',     'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'hands_on_hips',   'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'peace_sign',      'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'pointing',        'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'outstretched_arms','section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'beckoning',       'section' => 'pose', 'subsection' => 'arm_position', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'praying',         'section' => 'pose', 'subsection' => 'arm_position', 'post_count' => 100000, 'is_nsfw' => false],

            ['name' => 'legs_up',         'section' => 'pose', 'subsection' => 'leg_position', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'spread_legs',     'section' => 'pose', 'subsection' => 'leg_position', 'post_count' => 500000, 'is_nsfw' => true],
            ['name' => 'crossed_legs',    'section' => 'pose', 'subsection' => 'leg_position', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'knees_up',        'section' => 'pose', 'subsection' => 'leg_position', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'leg_lift',        'section' => 'pose', 'subsection' => 'leg_position', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'thigh_squeeze',   'section' => 'pose', 'subsection' => 'leg_position', 'post_count' =>  80000, 'is_nsfw' => true],
            ['name' => 'standing_split',  'section' => 'pose', 'subsection' => 'leg_position', 'post_count' =>  60000, 'is_nsfw' => false],

            ['name' => 'smile',           'section' => 'pose', 'subsection' => 'expression', 'post_count' => 3000000, 'is_nsfw' => false],
            ['name' => 'grin',            'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'blush',           'section' => 'pose', 'subsection' => 'expression', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => 'open_mouth',      'section' => 'pose', 'subsection' => 'expression', 'post_count' => 2500000, 'is_nsfw' => false],
            ['name' => 'closed_mouth',    'section' => 'pose', 'subsection' => 'expression', 'post_count' => 1500000, 'is_nsfw' => false],
            ['name' => 'angry',           'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'crying',          'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'surprised',       'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'embarrassed',     'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'expressionless',  'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'seductive_smile', 'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'tongue_out',      'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'ahegao',          'section' => 'pose', 'subsection' => 'expression', 'post_count' =>  150000, 'is_nsfw' => true],

            ['name' => 'pov',             'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 800000, 'is_nsfw' => false],
            ['name' => 'from_above',      'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'from_below',      'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'from_behind',     'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'close-up',        'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'full_body',       'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 800000, 'is_nsfw' => false],
            ['name' => 'upper_body',      'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 700000, 'is_nsfw' => false],
            ['name' => 'cowboy_shot',     'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'portrait',        'section' => 'pose', 'subsection' => 'camera_angle', 'post_count' => 300000, 'is_nsfw' => false],

            ['name' => 'sex',             'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 500000, 'is_nsfw' => true],
            ['name' => 'missionary',      'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'doggy_style',     'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'cowgirl_position','section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'oral',            'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 300000, 'is_nsfw' => true],
            ['name' => 'fellatio',        'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 250000, 'is_nsfw' => true],
            ['name' => 'paizuri',         'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'masturbation',    'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'bondage',         'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'restrained',      'section' => 'pose', 'subsection' => 'nsfw_pose', 'post_count' => 100000, 'is_nsfw' => true],

            // ── OUTFIT ────────────────────────────────────────────────────
            ['name' => 'shirt',           'section' => 'outfit', 'subsection' => 'top', 'post_count' => 800000, 'is_nsfw' => false],
            ['name' => 't-shirt',         'section' => 'outfit', 'subsection' => 'top', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'blouse',          'section' => 'outfit', 'subsection' => 'top', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'crop_top',        'section' => 'outfit', 'subsection' => 'top', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'tank_top',        'section' => 'outfit', 'subsection' => 'top', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'tube_top',        'section' => 'outfit', 'subsection' => 'top', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'sweater',         'section' => 'outfit', 'subsection' => 'top', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'hoodie',          'section' => 'outfit', 'subsection' => 'top', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'jacket',          'section' => 'outfit', 'subsection' => 'top', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'blazer',          'section' => 'outfit', 'subsection' => 'top', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'coat',            'section' => 'outfit', 'subsection' => 'top', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'cardigan',        'section' => 'outfit', 'subsection' => 'top', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'corset',          'section' => 'outfit', 'subsection' => 'top', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'bustier',         'section' => 'outfit', 'subsection' => 'top', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'turtleneck',      'section' => 'outfit', 'subsection' => 'top', 'post_count' => 200000, 'is_nsfw' => false],

            ['name' => 'skirt',           'section' => 'outfit', 'subsection' => 'bottom', 'post_count' => 1500000, 'is_nsfw' => false],
            ['name' => 'miniskirt',       'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  700000, 'is_nsfw' => false],
            ['name' => 'pleated_skirt',   'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'short_skirt',     'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'long_skirt',      'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'pencil_skirt',    'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>   80000, 'is_nsfw' => false],
            ['name' => 'pants',           'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'jeans',           'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'shorts',          'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'short_shorts',    'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'hot_pants',       'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'leggings',        'section' => 'outfit', 'subsection' => 'bottom', 'post_count' =>  150000, 'is_nsfw' => false],

            ['name' => 'dress',           'section' => 'outfit', 'subsection' => 'dress', 'post_count' => 1000000, 'is_nsfw' => false],
            ['name' => 'sundress',        'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'evening_gown',    'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'wedding_dress',   'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'mini_dress',      'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'kimono',          'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'yukata',          'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'qipao',           'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'gothic_lolita',   'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'lolita_fashion',  'section' => 'outfit', 'subsection' => 'dress', 'post_count' =>  150000, 'is_nsfw' => false],

            ['name' => 'bra',             'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 500000, 'is_nsfw' => true],
            ['name' => 'panties',         'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 700000, 'is_nsfw' => true],
            ['name' => 'thong',           'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'g-string',        'section' => 'outfit', 'subsection' => 'underwear', 'post_count' =>  80000, 'is_nsfw' => true],
            ['name' => 'no_bra',          'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 300000, 'is_nsfw' => true],
            ['name' => 'no_panties',      'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'lingerie',        'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 300000, 'is_nsfw' => true],
            ['name' => 'garter_belt',     'section' => 'outfit', 'subsection' => 'underwear', 'post_count' => 150000, 'is_nsfw' => true],

            ['name' => 'bikini',          'section' => 'outfit', 'subsection' => 'swimwear', 'post_count' => 700000, 'is_nsfw' => false],
            ['name' => 'micro_bikini',    'section' => 'outfit', 'subsection' => 'swimwear', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'string_bikini',   'section' => 'outfit', 'subsection' => 'swimwear', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'one-piece_swimsuit','section'=> 'outfit', 'subsection' => 'swimwear', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'school_swimsuit', 'section' => 'outfit', 'subsection' => 'swimwear', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'competition_swimsuit','section'=>'outfit','subsection' => 'swimwear', 'post_count' =>  80000, 'is_nsfw' => false],

            ['name' => 'high_heels',      'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'boots',           'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'knee_boots',      'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'thigh_boots',     'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'sneakers',        'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'sandals',         'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'mary_janes',      'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'barefoot',        'section' => 'outfit', 'subsection' => 'footwear', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'platform_heels',  'section' => 'outfit', 'subsection' => 'footwear', 'post_count' =>  80000, 'is_nsfw' => false],

            ['name' => 'thighhighs',      'section' => 'outfit', 'subsection' => 'legwear', 'post_count' => 1000000, 'is_nsfw' => false],
            ['name' => 'knee_socks',      'section' => 'outfit', 'subsection' => 'legwear', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'stockings',       'section' => 'outfit', 'subsection' => 'legwear', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'pantyhose',       'section' => 'outfit', 'subsection' => 'legwear', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'fishnet_stockings','section' => 'outfit', 'subsection' => 'legwear', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'white_thighhighs','section' => 'outfit', 'subsection' => 'legwear', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'black_thighhighs','section' => 'outfit', 'subsection' => 'legwear', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'striped_thighhighs','section'=>  'outfit','subsection' => 'legwear', 'post_count' =>  150000, 'is_nsfw' => false],

            ['name' => 'hat',             'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'beret',           'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'witch_hat',       'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'crown',           'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'tiara',           'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'headband',        'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'hair_bow',        'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 700000, 'is_nsfw' => false],
            ['name' => 'hair_ribbon',     'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'glasses',         'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'sunglasses',      'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'veil',            'section' => 'outfit', 'subsection' => 'headwear', 'post_count' => 100000, 'is_nsfw' => false],

            ['name' => 'necklace',        'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'choker',          'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'collar',          'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'earrings',        'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'bracelet',        'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'ring',            'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'bag',             'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'scarf',           'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'bow_tie',         'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'necktie',         'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'ribbon',          'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'cape',            'section' => 'outfit', 'subsection' => 'accessories', 'post_count' => 200000, 'is_nsfw' => false],

            ['name' => 'gloves',          'section' => 'outfit', 'subsection' => 'gloves', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'fingerless_gloves','section' => 'outfit', 'subsection' => 'gloves', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'elbow_gloves',    'section' => 'outfit', 'subsection' => 'gloves', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'long_gloves',     'section' => 'outfit', 'subsection' => 'gloves', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'latex_gloves',    'section' => 'outfit', 'subsection' => 'gloves', 'post_count' =>  50000, 'is_nsfw' => false],

            ['name' => 'school_uniform',  'section' => 'outfit', 'subsection' => 'uniform', 'post_count' => 1200000, 'is_nsfw' => false],
            ['name' => 'serafuku',        'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  600000, 'is_nsfw' => false],
            ['name' => 'maid',            'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'military_uniform','section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'nurse_uniform',   'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'shrine_maiden',   'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'miko',            'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'nun',             'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'magical_girl',    'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'armor',           'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'cheerleader',     'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'business_suit',   'section' => 'outfit', 'subsection' => 'uniform', 'post_count' =>  100000, 'is_nsfw' => false],

            ['name' => 'naked_apron',     'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 100000, 'is_nsfw' => true],
            ['name' => 'see-through',     'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 400000, 'is_nsfw' => true],
            ['name' => 'wet_clothes',     'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'torn_clothes',    'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'revealing_clothes','section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'latex',           'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' => 100000, 'is_nsfw' => true],
            ['name' => 'catsuit',         'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  80000, 'is_nsfw' => true],
            ['name' => 'harness',         'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  80000, 'is_nsfw' => true],
            ['name' => 'bondage_outfit',  'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  60000, 'is_nsfw' => true],
            ['name' => 'dominatrix',      'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  60000, 'is_nsfw' => true],
            ['name' => 'pasties',         'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  80000, 'is_nsfw' => true],
            ['name' => 'bodypaint',       'section' => 'outfit', 'subsection' => 'nsfw_outfit', 'post_count' =>  80000, 'is_nsfw' => true],

            // ── SCENE ─────────────────────────────────────────────────────
            ['name' => 'outdoors',        'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => 'forest',          'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'beach',           'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'mountain',        'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'garden',          'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'flower_field',    'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'ocean',           'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'lake',            'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'waterfall',       'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'desert',          'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'snow',            'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'cherry_blossoms', 'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'sky',             'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  800000, 'is_nsfw' => false],
            ['name' => 'clouds',          'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  600000, 'is_nsfw' => false],
            ['name' => 'starry_sky',      'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'underwater',      'section' => 'scene', 'subsection' => 'outdoor_nature', 'post_count' =>  200000, 'is_nsfw' => false],

            ['name' => 'city',            'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'street',          'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'rooftop',         'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'alley',           'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'park',            'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'train_station',   'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'bridge',          'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'ruins',           'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'shrine',          'section' => 'scene', 'subsection' => 'outdoor_urban', 'post_count' =>  150000, 'is_nsfw' => false],

            ['name' => 'indoors',         'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' => 1500000, 'is_nsfw' => false],
            ['name' => 'bedroom',         'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'bed',             'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  600000, 'is_nsfw' => false],
            ['name' => 'bathroom',        'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  200000, 'is_nsfw' => true],
            ['name' => 'bathtub',         'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  200000, 'is_nsfw' => true],
            ['name' => 'kitchen',         'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'living_room',     'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'japanese_room',   'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'windowsill',      'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'balcony',         'section' => 'scene', 'subsection' => 'indoor_home', 'post_count' =>  100000, 'is_nsfw' => false],

            ['name' => 'classroom',       'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'library',         'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'office',          'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'cafe',            'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'restaurant',      'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'hospital',        'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'gymnasium',       'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'locker_room',     'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 100000, 'is_nsfw' => true],
            ['name' => 'onsen',           'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 200000, 'is_nsfw' => true],
            ['name' => 'hotel_room',      'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 150000, 'is_nsfw' => true],
            ['name' => 'stage',           'section' => 'scene', 'subsection' => 'indoor_public', 'post_count' => 100000, 'is_nsfw' => false],

            ['name' => 'fantasy',         'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'castle',          'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'dungeon',         'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'magical_circle',  'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'floating_island', 'section' => 'scene', 'subsection' => 'fantasy', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'enchanted_forest','section' => 'scene', 'subsection' => 'fantasy', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'throne_room',     'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'ancient_ruins',   'section' => 'scene', 'subsection' => 'fantasy', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'heaven',          'section' => 'scene', 'subsection' => 'fantasy', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'void',            'section' => 'scene', 'subsection' => 'fantasy', 'post_count' =>  80000, 'is_nsfw' => false],

            ['name' => 'sci-fi',          'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'cyberpunk',       'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'futuristic',      'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'spaceship',       'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'space',           'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'outer_space',     'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'neon_lights',     'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'hologram',        'section' => 'scene', 'subsection' => 'scifi', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'laboratory',      'section' => 'scene', 'subsection' => 'scifi', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'post-apocalyptic','section' => 'scene', 'subsection' => 'scifi', 'post_count' =>  80000, 'is_nsfw' => false],

            ['name' => 'day',             'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 500000, 'is_nsfw' => false],
            ['name' => 'night',           'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 600000, 'is_nsfw' => false],
            ['name' => 'sunset',          'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'sunrise',         'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'dawn',            'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'dusk',            'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'morning',         'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'midnight',        'section' => 'scene', 'subsection' => 'time_of_day', 'post_count' =>  80000, 'is_nsfw' => false],

            ['name' => 'sunlight',        'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'moonlight',       'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'backlighting',    'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'dark',            'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'candlelight',     'section' => 'scene', 'subsection' => 'lighting', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'spotlight',       'section' => 'scene', 'subsection' => 'lighting', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'light_rays',      'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'bokeh',           'section' => 'scene', 'subsection' => 'lighting', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'dramatic_lighting','section' => 'scene', 'subsection' => 'lighting', 'post_count' => 100000, 'is_nsfw' => false],

            ['name' => 'rain',            'section' => 'scene', 'subsection' => 'weather', 'post_count' => 400000, 'is_nsfw' => false],
            ['name' => 'snow',            'section' => 'scene', 'subsection' => 'weather', 'post_count' => 300000, 'is_nsfw' => false],
            ['name' => 'cloudy',          'section' => 'scene', 'subsection' => 'weather', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'fog',             'section' => 'scene', 'subsection' => 'weather', 'post_count' => 150000, 'is_nsfw' => false],
            ['name' => 'wind',            'section' => 'scene', 'subsection' => 'weather', 'post_count' => 200000, 'is_nsfw' => false],
            ['name' => 'storm',           'section' => 'scene', 'subsection' => 'weather', 'post_count' => 100000, 'is_nsfw' => false],
            ['name' => 'rainbow',         'section' => 'scene', 'subsection' => 'weather', 'post_count' =>  80000, 'is_nsfw' => false],
            ['name' => 'sunny',           'section' => 'scene', 'subsection' => 'weather', 'post_count' => 100000, 'is_nsfw' => false],

            ['name' => 'masterpiece',     'section' => 'scene', 'subsection' => 'art_style', 'post_count' => 3000000, 'is_nsfw' => false],
            ['name' => 'best_quality',    'section' => 'scene', 'subsection' => 'art_style', 'post_count' => 2000000, 'is_nsfw' => false],
            ['name' => 'high_quality',    'section' => 'scene', 'subsection' => 'art_style', 'post_count' => 1000000, 'is_nsfw' => false],
            ['name' => 'ultra_detailed',  'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  800000, 'is_nsfw' => false],
            ['name' => 'detailed',        'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  600000, 'is_nsfw' => false],
            ['name' => 'realistic',       'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'photorealistic',  'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'anime',           'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'digital_art',     'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  300000, 'is_nsfw' => false],
            ['name' => 'watercolor',      'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => 'oil_painting',    'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  150000, 'is_nsfw' => false],
            ['name' => 'sketch',          'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  400000, 'is_nsfw' => false],
            ['name' => 'cel_shading',     'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  100000, 'is_nsfw' => false],
            ['name' => 'monochrome',      'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  500000, 'is_nsfw' => false],
            ['name' => 'pixel_art',       'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  200000, 'is_nsfw' => false],
            ['name' => '3dcg',            'section' => 'scene', 'subsection' => 'art_style', 'post_count' =>  200000, 'is_nsfw' => false],
        ];

        $inserted = 0;
        foreach ($tags as $tag) {
            Tag::firstOrCreate(['name' => $tag['name']], $tag);
            $inserted++;
        }

        $this->command->info("TagSeeder: {$inserted} tags processed.");
    }
}
